# Snakemake configuration for experiment engine

# Base output directory for Parquet files
base_out: "results/parquet"

# Directory containing CSV files to convert
csv_dir: "experiments/deletion_capacity/results"

# Output granularity - "seed" for one row per seed, "event" for one row per event
granularity: "seed"

# Optional: Specific patterns to include/exclude
include_patterns:
  - "*.csv"

exclude_patterns:
  - "**/tmp/**"
  - "**/.git/**"

# DuckDB settings
duckdb:
  memory_limit: "4GB"
  temp_directory: "/tmp/duckdb"